version: '3.9'

services:
  postgres_user_service:
    image: postgres
    container_name: postgres_user_service
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_user_data:/var/lib/postgresql/data

  postgres_music_service:
    image: postgres
    container_name: postgres_music_service
    environment:
      POSTGRES_DB: music_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_music_data:/var/lib/postgresql/data

  postgres_auth_service:
    image: postgres
    container_name: postgres_auth_service
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5434:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  minio_streaming_service:
    image: minio/minio:latest
    container_name: minio_streaming_service
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_streaming_data:/data

volumes:
  postgres_user_data:
  postgres_music_data:
  postgres_auth_data:
  minio_streaming_data:
