minio:
  url: ${MINIO_URL:http://localhost:9002}
  access-key: minioadmin
  secret-key: minioadmin
  bucket: audio

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  kafka:
    bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}
