server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=1

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/api/user/**
              filters:
                - StripPrefix=1

            - id: music-service-albums
              uri: lb://music-service
              predicates:
                - Path=/api/albums/**
              filters:
                - StripPrefix=1

            - id: music-service-tracks
              uri: lb://music-service
              predicates:
                - Path=/api/tracks/**
              filters:
                - StripPrefix=1

            - id: music-service-artists
              uri: lb://music-service
              predicates:
                - Path=/api/artists/**
              filters:
                - StripPrefix=1

            - id: music-service-playlists
              uri: lb://music-service
              predicates:
                - Path=/api/playlists/**
              filters:
                - StripPrefix=1

            - id: music-service-user
              uri: lb://music-service
              predicates:
                - Path=/api/user/music/**
              filters:
                - StripPrefix=1

            - id: music-service-search
              uri: lb://music-service
              predicates:
                - Path=/api/search
              filters:
                - StripPrefix=1

            - id: music-service-stream
              uri: lb://music-service
              predicates:
                - Path=/api/stream/**
              filters:
                - StripPrefix=1

            - id: streaming-service-stream
              uri: lb://streaming-service
              predicates:
                - Path=/api/audio/**
              filters:
                - StripPrefix=1

            - id: image-service
              uri: lb://image-service
              predicates:
                - Path=/api/images/**
              filters:
                - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
