server.port=8083
spring.application.name=music-service

spring.datasource.url=jdbc:postgresql://localhost:5433/music_db
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

jwt.secret=9XU6885Woh6W2k52VBhvrCrl1JTxEeub
track-uploaded-topic=track-uploaded
track-group=track-group